spring.application.name=ex7
spring.config.import=file:.env[.properties]
# Spring Security
logging.level.org.springframework.security=TRACE
# Github Login
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}